import google.generativeai as genai
from dotenv import load_dotenv
import os 
load_dotenv(override=True)

class ChatBotService():
    
    def __init__(self) -> None:
        self.GOOGLE_API_KEY = os.environ.get("GOOGLE_API_KEY")
        genai.configure(api_key=self.GOOGLE_API_KEY)
        self.model_name = os.environ.get("PRIMARY_MODEL_NAME")
        self.model = genai.GenerativeModel(self.model_name)
        
    
    def get_general_answer(self, user_query):
        try:
            response = self.model.generate_content(
                user_query.question,
                safety_settings={
                    'HATE': 'BLOCK_NONE',
                    'HARASSMENT': 'BLOCK_NONE',
                    'SEXUAL' : 'BLOCK_NONE',
                    'DANGEROUS' : 'BLOCK_NONE'
                })
            check_data = response.text
            
            # check_data can be NONE if the reponse is the unsafefy text
            # return the reponse if the response text is safe
            
            if check_data is not None:
                return check_data
            else:
                return "No information generated by the model"
            
        except Exception as e:
            return e
    
    def get_user_intention(self, user_query):
        prompt = f"""
        Classify the following user query into one of these intents: recommendation, order, general.
        User Query: "{user_query}"
        Intent:
        """
        try:
            response = self.model.generate_content(
                prompt,
                safety_settings={
                    'HATE': 'BLOCK_NONE',
                    'HARASSMENT': 'BLOCK_NONE',
                    'SEXUAL': 'BLOCK_NONE',
                    'DANGEROUS': 'BLOCK_NONE'
                }
            )
            intent_response = response.text.strip()
            intent = "general"
            if "recommendation" in intent_response:
                intent = "recommendation"
            elif "order" in intent_response:
                intent = "order"
            elif "general" in intent_response:
                intent = "general"
            return intent
        except Exception as e:
            print(f"Error generating content: {e}")
            return None