version: '3.9'
services:
  db:
    build:
      context: ./database/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env  
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_LOG_BIN=ON
      - MYSQL_LOG_BIN_TRUST_FUNCTION_CREATORS=ON
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_general_ci
    volumes:
      - ./database/mariadb/db/:/var/lib/mysql   
    networks:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./.env:/app/.env
    networks:
      - backend

  adminer:
    image: adminer
    ports:
      - 8080:8080
    links:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge