name: generative_ai_gemina_flutter
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  flutter_chat_ui: ^1.6.14
  file_picker: ^8.0.5
  image_picker: ^1.1.2
  open_filex: ^4.4.0
  uuid: ^4.4.0
  flutter_svg: ^2.0.10+1
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  http: ^1.2.1
  path_provider: ^2.1.3
  equatable: ^2.0.5
  flutter_carousel_widget: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/logo/logo.png
    - assets/certificates/
    - assets/certificates/cert.pem
    - assets/certificates/key.pem
    - assets/certificates/test.txt
    - assets/message.json
    - assets/icons/
    - assets/icons/gemini_logo.svg
    - assets/icons/61-trash.svg
