version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.9.6
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
    driver: local