version: '3.8'

services:
  db:
    image: mariadb:10.5
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_LOG_BIN=ON
      - MYSQL_LOG_BIN_TRUST_FUNCTION_CREATORS=ON
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_general_ci
    volumes:
      - ./db/mariadb/data:/var/lib/mysql
    ports:
      - "${DB_PORT}:${DB_PORT}"
    command: --bind-address=0.0.0.0
