version: "3.9"
services:
    chatbot:
      container_name: chatbot-service
      build:
        context: .
        dockerfile: Dockerfile 
      env_file:
          - .env
      ports:
        - "8000:8000"  
      volumes:
        - ./:/opt/app
      working_dir: /opt/app
      entrypoint: ["python", "main.py"]
      profiles: ["chatbot-service"]
      networks:
        - backend
        
networks:
  backend:
    driver: bridge